# Generated by Django 3.2.13 on 2023-05-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient_type',
            fields=[
                ('nutrient_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nutrient_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nutrient_type',
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('nutrient_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nutrient_name', models.TextField()),
                ('nutrient_image_url', models.TextField()),
                ('nutrient_brand', models.TextField()),
                ('nutrient_intake', models.TextField()),
                ('nutrient_caution', models.TextField()),
                ('nutrient_expiration', models.TextField()),
                ('nutrient_material', models.TextField()),
                ('nutrient_pregnant', models.BooleanField()),
                ('nutrient_child', models.BooleanField()),
                ('nutrient_gender', models.IntegerField()),
                ('nutrient_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend_nutrients.nutrient_type')),
            ],
            options={
                'db_table': 'nutrient',
            },
        ),
    ]
